### ISSUE TITLE
Change Name

### ISSUE THREAD

**Issue by Diogovski** [sanity-io/sanity-plugin-graph-view#5]
![image](https://user-images.githubusercontent.com/81532541/165389561-e6aa33a5-b962-432a-aec2-bf89de3fc7d4.png)

Hi is it possible to change this names?

**Comment by Diogovski** [comment]
I see that it is the names of my schema files 
![image](https://user-images.githubusercontent.com/81532541/165389687-50f3ae19-3b14-40a7-a63a-22c57368160c.png)

but i wanted to know if i can change them without needing to change my files names!

**Comment by Diogovski** [comment]
Ohhh okay okay, but can i change it?

**Comment by atombender** [comment]
Unfortunately, no, the legend box always shows the types. You can only change it by changing the names of your types. Feel free to submit a PR, though.
